# Default values for timed-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
backend:
  replicaCount: 1
  image:
    repository: adfinissygroup/timed-backend
     # Specify a tag to override which version of timed to deploy.
     # If no tag is specified the appVersion from Chart.yaml is used as tag.
     # tag:
    pullPolicy: IfNotPresent
  service:
    # Specifiy secret for authentication.
    # If not random token will be generated
    # secret:
    name: timed-backend
    type: ClusterIP
    externalPort: 80
    internalPort: 80
  resources:
    {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  settings:
    # django settings for backend
    emailUrl: smtp://localhost:25
    emailFrom: webmaster@chart-example.local
    serverEmail: webmaster@chart-example.local

frontend:
  replicaCount: 1
  image:
    repository: adfinissygroup/timed-frontend
    # Specify a tag to override which version of timed to deploy.
    # If no tag is specified the appVersion from Chart.yaml is used as tag.
    # tag:
    pullPolicy: IfNotPresent
  service:
    name: timed-frontend
    type: ClusterIP
    externalPort: 80
    internalPort: 80
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  livenessProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1
  readinessProbe:
    enabled: true
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
    successThreshold: 1

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts: []
  #  - timed-test.example.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - timed-test.example.com

postgresql:
  enabled: true
  postgresqlDatabase: timed
  postgresqlUsername: postgres
  image:
    tag: 12.2.0
